sudo: required
services:
  - docker

before_install:
  - docker build -t mfshair01/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true mfshair01/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "Environments"
  env: "Docker-environment-env"
  bucket_name: "elasticbeanstalk-eu-north-1-295550966758"
  bucket_path: "Environments"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY  
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  

